services:
  # AI Worker only - connects to external RabbitMQ
  ai-worker:
    image: ghcr.io/eduva/eduva-ai-generator:latest
    container_name: ai-worker
    environment:
      # RabbitMQ Configuration (external)
      RABBITMQ_URI: ${RABBITMQ_URI}
      AI_TASK_QUEUE: ${AI_TASK_QUEUE}
      DLQ_QUEUE: ${DLQ_QUEUE}
      DLQ_EXCHANGE: ${DLQ_EXCHANGE}
      MAIN_EXCHANGE: ${MAIN_EXCHANGE}
      ROUTING_KEY: ${ROUTING_KEY}

      # DLQ Configuration
      DLQ_MONITORING_ENABLED: ${DLQ_MONITORING_ENABLED}
      DLQ_ALERT_THRESHOLD: ${DLQ_ALERT_THRESHOLD}
      MAX_RETRIES: ${MAX_RETRIES}

      # Azure Configuration
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_INPUT_CONTAINER: ${AZURE_INPUT_CONTAINER}
      AZURE_OUTPUT_CONTAINER: ${AZURE_OUTPUT_CONTAINER}

      # Backend API Configuration
      BACKEND_API_BASE_URL: ${BACKEND_API_BASE_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}

      # AI Service Configuration
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DEFAULT_MODEL: ${DEFAULT_MODEL}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}
      PEXELS_ACCESS_KEY: ${PEXELS_ACCESS_KEY}

      # Backward compatibility
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME}
    volumes:
      - ./credentials:/app/credentials

    restart: unless-stopped
