# Product Worker Only - High Performance VPS
services:
  product-worker:
    image: ghcr.io/tranduckhuy/eduva-ai-product-worker:latest
    container_name: product-worker
    environment:
      # RabbitMQ Configuration
      RABBITMQ_URI: ${RABBITMQ_URI}
      QUEUE_NAME: ${QUEUE_NAME}
      EXCHANGE_NAME: ${EXCHANGE_NAME}
      ROUTING_KEY: ${ROUTING_KEY}

      # Storage Configuration
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_INPUT_CONTAINER: ${AZURE_INPUT_CONTAINER}
      AZURE_OUTPUT_CONTAINER: ${AZURE_OUTPUT_CONTAINER}

      # Backend Communication
      BACKEND_API_BASE_URL: ${BACKEND_API_BASE_URL}
      BACKEND_API_KEY: ${BACKEND_API_KEY}

      # AI Configuration
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      DEFAULT_MODEL: ${DEFAULT_MODEL}

      # Product Worker Specific (Heavy processing)
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_LOCATION: ${GOOGLE_CLOUD_LOCATION}
      IMAGE_GENERATION_MODEL: ${IMAGE_GENERATION_MODEL}
      UNSPLASH_ACCESS_KEY: ${UNSPLASH_ACCESS_KEY}

      # Prefetch Count for RabbitMQ
      PREFETCH_COUNT: ${PREFETCH_COUNT}

    volumes:
      - /etc/huytde_work/credentials:/app/credentials:ro

    restart: unless-stopped
