name: Deploy Eduva AI Generator Image

on:
  workflow_run:
    workflows: ["Publish AI Generator Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AI Generator Worker
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run with Docker Compose
        run: |
          echo "Pulling latest Docker images..."
          docker compose pull
          echo "Recreating containers with latest images..."
          docker compose -f docker-compose.yaml up --force-recreate --build -d
          echo "Cleaning up unused Docker images..."
          docker image prune -f
          echo "Deployment completed successfully."
