name: Publish Eduva AI Generator Image

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish AI Generator Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker buildx build . \
            --tag ghcr.io/${{ github.repository_owner }}/eduva-ai-generator:latest \
            --tag ghcr.io/${{ github.repository_owner }}/eduva-ai-generator:${{ github.sha }} \
            --platform linux/amd64,linux/arm64 \
            --push \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache
